name: Check new SFDX version

on:
  repository_dispatch:
    types: manual-sfdx-update
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate PKGBUILD
        id: generate-pkgbuild
        run: cd sfdx-cli && ../scripts/generate-sfdx-cli-pkgbuild.sh
      - name: Debug print new PKGBUILD
        run: cat sfdx-cli/PKGBUILD
      - name: Copy PKGBUILD to Docker context directory
        run: cp sfdx-cli/PKGBUILD .github/actions/generate-srcinfo/PKGBUILD
      - name: Generate SRCINFO in Docker
        id: generate-srcinfo
        uses: ./.github/actions/generate-srcinfo
      - name: Create SRCINFO file
        run: echo '${{ steps.generate-srcinfo.outputs.srcinfo }}' > sfdx-cli/.SRCINFO
      - name: Clean up
        run: rm .github/actions/generate-srcinfo/PKGBUILD
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          commit-message: "Updated sfdx-cli to version ${{ steps.generate-srcinfo.outputs.version }}"
          title: "Update sfdx-cli"
          branch: updates/sfdx-cli
          labels: sfdx-cli
          token: ${{ secrets.PERSONAL_TOKEN }}
