name: Build and Test SFDX-CLI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy files into Docker context directory
        run: cp -R ./sfdx-cli ./.github/actions/sfdx-test
      - name: Test Package
        uses: ./.github/actions/sfdx-test
      - name: Clean up
        run: rm -rf ./.github/actions/sfdx-test
      - name: Merge
        if: success() && github.head_ref == 'updates/sfdx-cli'
        uses: pascalgn/automerge-action@v0.7.5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MERGE_LABELS: sfdx-cli
          MERGE_METHOD: rebase
