name: Build and Test SFDX-CLI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy files into Docker context directory
        run: cp -R ./sfdx-cli ./.github/actions/sfdx-test
      - name: Test Package
        uses: ./.github/actions/sfdx-test
      - name: Clean up
        run: rm -rf ./.github/actions/sfdx-test && echo '${{ github.ref }}'
      - name: Merge
        if: success() && github.ref == 'refs/heads/updates/sfdx-cli'
        uses: devmasx/merge-branch@v1.1.0
        with:
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
