name: Test and Release SFDX-CLI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy files into Docker context directory
        run: cp -R ./sfdx-cli ./.github/actions/sfdx-test
      - name: Test Package
        uses: ./.github/actions/sfdx-test
      - name: Clean up
        run: rm -rf ./.github/actions/sfdx-test
      - name: Merge
        if: success() && github.head_ref == 'updates/sfdx-cli'
        uses: pascalgn/automerge-action@v0.7.5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MERGE_LABELS: "" # Somehow the workflow does not see the label set by earlier workflows
          MERGE_METHOD: rebase

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy private key to Git Docker image
        run: echo "${{ secrets.AUR_PRIVATE_KEY }}" > ./.github/actions/aur/id_rsa
      - name: Copy package files to Git Docker image
        run: cp -R sfdx-cli/. ./.github/actions/aur/
      - name: Handle AUR Git repository
        uses: ./.github/actions/aur
